### ISSUE TITLE
Add support for creating a redislite instance that is a slave of another redis server

### ISSUE THREAD

**Issue by dwighthubbard** [yahoo/redislite#34]
It would be useful to be able to create a redislite instance that is a slave of another redis server.

**Comment by reneighbor** [comment]
* slave configs get consumed in the "configuration.py" file, which has a long `template` string. The variables relevant to setting up slaving must be templated out only if those variables (ie masterport, masterip) are set; else do not pass those comments out. Task is to add jinja logic to config.py's `template` variable.
* Additionally, config-related variables are pased to the redis.StrictRedis()/redis.redis(). Need to seperate the config vs super() variables so that setting config variables don't trigger an unexpected argument error.

**Comment by dwighthubbard** [comment]
We got this committed and is in the most recent package build on PyPi reneighbor.

**Comment by reneighbor** [comment]
Wonderful!

On Fri, Apr 17, 2015 at 2:00 PM, Dwight Hubbard <notifications@github.com>
wrote:

> We got this committed and is in the most recent package build on PyPi
> reneighbor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yahoo/redislite/issues/34#issuecomment-94040089>.
>



-- 
Renee Chu
