### ISSUE TITLE
The settings default dictionary is not getting copied before being updated

### ISSUE THREAD

**Issue by dwighthubbard** [yahoo/redislite#53]

**Comment by reneighbor** [comment]
See configuration.py, config() takes the kwargs from the user and uses those to override any default settings (in the global default_settings dict). However the global default_settings variable is getting overridden so that if a user edits the default configs, those defaults will be edited for future users.

Task: Copy over default_settings before modifying, and write unit tests to ensure that the global variable isn't getting changed.

**Comment by dwighthubbard** [comment]
Thank you for the fix.  Awesome job.

This fix has been committed, marking this issue as closed.
